name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          java-version: 1.8
          distribution: zulu
      - uses: actions/setup-node@v3
        with:
          node-version: 12
      - run: npm ci
      - run: node ./meta-tools/compile-readme.js
      - name: Linting
        run: npm run lint
      - run: zip build.zip -r .
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Build
          path: build.zip
