name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Setup DITA-OT
        run: wget https://github.com/dita-ot/dita-ot/releases/download/3.5.1/dita-ot-3.5.1.zip && unzip dita-ot-3.5.1.zip
      - name: Add DITA-OT to path
        run: export PATH=$PATH:./dita-ot-3.5.1/bin
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - run: zip build.zip -r .
      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: Build
          path: build.zip
