name: Node.js Package

on:
  push:
    tags:
      - 'v[0-9]*.[0-9]*.[0-9]*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Setup DITA-OT
        run: wget https://github.com/dita-ot/dita-ot/releases/download/3.5.1/dita-ot-3.5.1.zip && unzip dita-ot-3.5.1.zip -d ../dita-ot
      - name: Add DITA-OT to path
        run: echo "::add-path::/home/runner/work/dita-ot-helper/dita-ot/dita-ot-3.5.1/bin"
      - run: which dita
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - name: Linting
        run: npm run lint
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
